### ISSUE TITLE
Implement "check_flat_directory_structure" check

### ISSUE THREAD

**Issue by imincik** [linz/geospatial-data-lake#153]
As discussed, make this part of the `check_stac_metadata` job:

- We're traversing the metadata files anyway, so there would be a lot of code duplication otherwise.
- If we had been planning to run `check_flat_directory_structure` and `check_stac_metadata` in parallel we could've done them both a bit faster, but with the current infrastructure we would be running them in serial. So rather than the ~100% overhead of running them in serial we can get a small overhead on `check_stac_metadata` to also check the flat structure.

**Comment by l0b0** [comment]
Things to check:

- URLs which we don't traverse, that is, `rel=self` and `rel=root`.
- Should ignore repeated directory separators. That is, treat `foo/bar` and `foo//bar` as the same path.
- Only check the actual path. That is, in `https://s3.foo/path/root.json?foo=a/b&baz=c/d#e/f`, ignore everything except `/path/root.json`.
- Decode a single level of URL escaping, so that `foo%2Fbar` is treated like `foo/bar`, but `foo%252Fbar`(decoded to literally `foo%2Fbar`)  is not.
