### ISSUE TITLE
Implement "content_iterator" step

### ISSUE THREAD

**Issue by imincik** [linz/geospatial-data-lake#164]
Implement "content_iterator" step

**Comment by l0b0** [comment]
Where is the state meant to live? We could

- traverse the metadata to find all the URLs + checksums and pass the state of this recursive search around,
- store the list of *all* URLs + checksums somewhere semi-permanent and pass the index around, *or*
- pass the list of *unprocessed* URLs + checksums around and modify it as we finish processing.

Some relevant considerations:

- If the list isn't enormous I would generally prefer passing it around to avoid having to deal with additional storage complexity.
- If we pass around the full data rather than references to storage we are much more likely to run into hard AWS limits. I'm not sure *how* likely, but IIRC we need to be able to deal with millions of files in a dataset.
- If we need to traverse the list more than once (and we probably do, since we'll want to separate checksum validation from copying files around) then we need some way to keep the full list around for multiple jobs.
- Recursing through the metadata repeatedly is going to be costly, but could allow some code reuse.

Is there anywhere convenient to store this for the lifetime of a batch execution? Do batch runs have some built-in state storage which is easy to read/write? If not, S3 or DynamoDB seem like obvious choices.

In a local system and with metadata size << RAM size I would expect to implement this as follows:

1. Some job collects all the URLs and checksums from the metadata. This could happen during metadata validation for efficiency, even though that means that job being responsible for more than one thing. This list is passed up the stack to the orchestrator.
2. The orchestrator passes the full list to the content iterator.
3. The content iterator validates N checksums in parallel.
4. Repeat until end of list.
5. The orchestrator passes the full list to the file copying job.

**Comment by l0b0** [comment]
Closed since this is effectively a task of #4.
