### ISSUE TITLE
Move user roles back to separate users stack

### ISSUE THREAD

**Issue by imincik** [linz/geospatial-data-lake#619]
Move "users-role" back to separate users stack which was changed in 0c44ffb6d32aedf626719a9547a0cfea189ada41 . This will allow us to exclude this role from deleting (and breaking Azure AD configuration) when re-deploying stacks

**Comment by l0b0** [comment]
Is it not possible to exclude a role from being deleted simply by setting its [removal policy](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.core/RemovalPolicy.html)? I don't think we need to move it to a separate stack to do that.

If we want to move the role to a separate stack we need to understand how to do it without returning to the situation where we can't deploy the stack because "it's in use by the API stack", as reported by CDK before commit 0c44ffb6d32aedf626719a9547a0cfea189ada41. I can't find references to a similar issue so far, although many users are mentioning the same error message when trying to *remove* a reference to an existing stack (which is a solved problem). It's possible the issue is that CDK is redeploying parts of the infrastructure it really shouldn't be redeploying. If that is the case we should probably fix those issues separately.

**Comment by imincik** [comment]
@l0b0  , currently (without knowing more details) I don't see any reason why we should have those dependency issues. We can have them only in case when `users` stack is deleted before `api` stack or we have some circular dependencies in between those stacks. So if CDK deletes stacks in incorrect order, I would like to see it and try to fix it. 

This means I still like having separate `users` stack more than implementing workaround using removal policy.

**Comment by imincik** [comment]
I guess we where hitting this kind of problems with CloudFormation Exports - https://github.com/aws/aws-cdk/issues/5304

**Comment by imincik** [comment]
And we still hit this problem in current master - https://github.com/linz/geospatial-data-lake/runs/2444942934?check_suite_focus=true#step:13:349

**Comment by imincik** [comment]
One solution can be using  SSM parameters instead of passing cdk resources between stacks

**Comment by imincik** [comment]
Discussed and original argument to be able to keep users stack from deleting doesn't make a sense anymore but we can create new task to prevent deletion of users role by setting removal policy.

**Comment by MitchellPaff** [comment]
add the readonly role to this stack also.

**Comment by l0b0** [comment]
Should we move LDS role as well?

**Comment by imincik** [comment]
> Should we move LDS role as well?

I don't think so. It is very specific to our use case.

**Comment by imincik** [comment]
I am closing this task as not possible to implement and not worth of issues it can introduce. I extracted some useful changes from #669 to separate PR and will be happy with that.
